In [1]:
import numpy as np

__1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

$\begin{vmatrix}
-1-\lambda & -6\\ 
2 & 6-\lambda
\end{vmatrix} = 0$

$(-1-\lambda)(6-\lambda)+12=0$

$\lambda^2-5\lambda+6=0$

$D=1$

$\lambda_1=3, \lambda_2=2$

$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}
\begin{pmatrix}
x_1\\ 
x_2
\end{pmatrix}=3\begin{pmatrix}
x_1\\ 
x_2
\end{pmatrix}$

$\begin{cases}
-x_1-6x_2=3x_1 \\
2x_1+6x_2=3x_2
\end{cases}$

$-6x_2=4x_1$

$x_1=-1.5x_2$

$-3x_2+6x_2-3x_2=0$

$x_1=0, x_2=0$

$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}
\begin{pmatrix}
x_1\\ 
x_2
\end{pmatrix}=2\begin{pmatrix}
x_1\\ 
x_2
\end{pmatrix}$

$\begin{cases}
-x_1-6x_2=2x_1 \\
2x_1+6x_2=2x_2
\end{cases}$

$-6x_2=3x_1$

$x_1=-2x_2$

$-4x_2+6x_2=2x_2$

$x_1=2, x_2=-1$

In [2]:
a = np.array([[-1,-6], [2,6]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')



print(f'v1\n{v.T[1]}')
print(f'v1\n{v[:, 1]}')
print(f'\n{v.T[1].dot(v.T[1])}')

Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]
v1
[ 0.83205029 -0.5547002 ]
v1
[ 0.83205029 -0.5547002 ]

1.0


__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.

$\begin{vmatrix}
-1-\lambda & 0\\ 
0 & -1-\lambda
\end{vmatrix} = 0$

$(-1-\lambda)^2=0$

$\lambda=-1$

$\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}
\begin{pmatrix}
x_1\\ 
x_2
\end{pmatrix}=-1\begin{pmatrix}
x_1\\ 
x_2
\end{pmatrix}$

Т.к. -1 равен $\lambda$, то все векторы - собственные.

In [3]:
a = np.array([[-1,0], [0,-1]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')



print(f'v1\n{v.T[1]}')
print(f'v1\n{v[:, 1]}')
print(f'\n{v.T[1].dot(v.T[1])}')

Матрица A:
[[-1  0]
 [ 0 -1]]
Собственные значения:
[-1. -1.]
Собственные векторы:
[[1. 0.]
 [0. 1.]]
v1
[0. 1.]
v1
[0. 1.]

1.0


__3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

$\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}
\begin{pmatrix}
1\\ 
1
\end{pmatrix}=\lambda\begin{pmatrix}
1\\ 
1
\end{pmatrix}$

$
\begin{cases}
\lambda=2\\ 
\lambda=2
\end{cases}
\Rightarrow
\lambda=2$

Таким образом, вектор $x=(1,1)$ является собственным вектором линейного оператора, заданного матрицей $A$, и его собственное значение составляет $\lambda=2$

In [4]:
a = np.array([[1,1], [-1,3]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')



print(f'v1\n{v.T[1]}')
print(f'v1\n{v[:, 1]}')
print(f'\n{v.T[1].dot(v.T[1])}')

Матрица A:
[[ 1  1]
 [-1  3]]
Собственные значения:
[2.00000002 1.99999998]
Собственные векторы:
[[ 0.70710677 -0.70710679]
 [ 0.70710679 -0.70710677]]
v1
[-0.70710679 -0.70710677]
v1
[-0.70710679 -0.70710677]

1.0


__4.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}
\begin{pmatrix}
3\\
-3\\
-4
\end{pmatrix}=\lambda\begin{pmatrix}
3\\
-3\\
-4
\end{pmatrix}$

$
\begin{cases}
\lambda=-3\\
\lambda=-3\\
\lambda=3
\end{cases}$

Таким образом, вектор $x=(3,-3,-4)$ не является собственным вектором линейного оператора, заданного матрицей $A$.

In [5]:
a = np.array([[0,3,0], [3,0,0], [0,0,3]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')



print(f'v1\n{v.T[1]}')
print(f'v1\n{v[:, 1]}')
print(f'\n{v.T[1].dot(v.T[1])}')

Матрица A:
[[0 3 0]
 [3 0 0]
 [0 0 3]]
Собственные значения:
[ 3. -3.  3.]
Собственные векторы:
[[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
v1
[-0.70710678  0.70710678  0.        ]
v1
[-0.70710678  0.70710678  0.        ]

1.0
