In [1]:
import numpy as np

## Матрицы и матричные операции. Часть 1

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
   
   $AB$ не определено, т.к. $2\neq4$
   
   $BA$ не определено, т.к. $4\neq2$
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
   
   $AB$ определено, т.к. $5=5$, получится матрица $C$ ($2\times 3$)
   
   $BA$ не определено, т.к. $3\neq2$
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
   
   $AB$ определено, т.к. $3=3$, получится матрица $C$ ($8\times 8$)
   
   $BA$ определено, т.к. $8=8$, получится матрица $C$ ($3\times 3$)
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.
   
   $AB$ определено, т.к. $4=4$, получится матрица $C$ ($4\times 4$)
   
   $BA$ определено, т.к. $4=4$, получится матрица $C$ ($4\times 4$)

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$A+B=\begin{pmatrix}
1+4 & (-2)+(-1)\\ 
3+0 & 0+5
\end{pmatrix}=
\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}
$

$AB=\begin{pmatrix}
1\cdot 4 + (-2)\cdot 0 & 1\cdot(-1)+(-2)\cdot 5\\ 
3\cdot 4+0\cdot 0 & 3\cdot (-1)+0\cdot 5
\end{pmatrix}=
\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}
$

In [12]:
A=np.array([[1,-2],[3,0]])
B=np.array([[4,-1],[0,5]])

print(f'A+B=\n{A+B}\n')
print(f'AB=\n{A@B}\n')

A+B=
[[ 5 -3]
 [ 3  5]]

AB=
[[  4 -11]
 [ 12  -3]]



__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$3A-2B+4C$=$3\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$$-2\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$$+4\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}$=$\begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix}$$-\begin{pmatrix}
0 & 10\\ 
4 & -2
\end{pmatrix}$$+\begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix}$=$\begin{pmatrix}
3 & 11\\ 
5 & -16
\end{pmatrix}$$+\begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix}$=$\begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$

In [13]:
A = np.array([[1,7],[3, -6]])
B = np.array([[0,5],[2, -1]])
C = np.array([[2,-4],[1, 1]])

print(f'3A-2B+4C=\n{3*A - 2*B + 4*C}\n')

3A-2B+4C=
[[ 11  -5]
 [  9 -12]]



__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

$A^T=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}$

$AA^T=\begin{pmatrix}
4\cdot4+1\cdot1 & 4\cdot5+1\cdot(-2) & 4\cdot2+1\cdot3\\
5\cdot4+(-2)\cdot1 & 5\cdot5+(-2)\cdot(-2) & 5\cdot2+(-2)\cdot3\\
2\cdot4+3\cdot1 & 2\cdot5+3\cdot(-2) & 2\cdot2+3\cdot3
\end{pmatrix}=\begin{pmatrix}
17 & 18 & 11\\
18 & 29 & 4\\
11 & 4 & 13
\end{pmatrix}$

$A^TA=\begin{pmatrix}
4\cdot4+5\cdot5+2\cdot2 & 4\cdot1+5\cdot(-2)+2\cdot3\\ 
1\cdot4+(-2)\cdot5+3\cdot2 & 1\cdot1+(-2)\cdot(-2)+3\cdot3
\end{pmatrix}=\begin{pmatrix}
45 & 0\\ 
0 & 14
\end{pmatrix}$

In [18]:
A = np.array([[4,1],[5, -2],[2,3]])

print(f'A*A.T=\n{A@A.T}\n')
print(f'A.T*A=\n{A.T@A}\n')

A*A.T=
[[17 18 11]
 [18 29  4]
 [11  4 13]]

A.T*A=
[[45  0]
 [ 0 14]]



__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [6]:
def dot_product(a, b):
    a_rows = len(a)
    b_rows = len(b)
    a_cols = len(a[0])
    b_cols = len(b[0])
    if a_cols != b_rows:
        print('Number of columns in A must be equal to number of rows in B')
        return False
    result = [[0]*b_cols for i in range(a_rows)]
    for i in range(a_rows):
        for j in range(b_cols):
            for k in range(a_cols):
                result[i][j] += a[i][k] * b[k][j]
    return result

## Матрицы и матричные операции. Часть 2

__1.__ Вычислить определитель:

   a)

$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix}=sin^2x+cos^2x=1$

   б)
    
$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix}=4\cdot5\cdot9+2\cdot1\cdot0+0\cdot0\cdot3-3\cdot5\cdot0-2\cdot0\cdot9-4\cdot1\cdot0=180$
    
   в)

$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}=1\cdot5\cdot9+2\cdot6\cdot7+3\cdot4\cdot8-3\cdot5\cdot7-1\cdot6\cdot8-2\cdot4\cdot9=0$

In [24]:
a=np.array([[4,2,3],[0,5,1],[0,0,9]])
b=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(f'Определитель для б ={np.linalg.det(a)}\n')
print(f'Определитель для в ={np.linalg.det(b):.0f}\n')

Определитель для б =180.0

Определитель для в =-0



__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$
   
   $det(AB)=detA\cdot detB$
   
   $det(A^{2})=16$
       
   б) $det(A^{T})$
   
   $det(A^{T})=detA=4$
    
   в) $det(2A)$
   
   $det(2A)=2detA=8$
   
   

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

Строка 2 равна строке 1 умноженной на -2.

$\begin{vmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{vmatrix}=(-2)\cdot(-14)\cdot13+7\cdot6\cdot(-3)+(-3)\cdot4\cdot7-(-3)\cdot(-14)\cdot(-3)-(-2)\cdot6\cdot7-7\cdot4\cdot13=0$

Определитель = 0, матрица вырожденная.

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   3 строка является суммой первых двух, ее можно отбросить.
   
   $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1
\end{pmatrix}$

   Из 2 строки вычитаем 1.
   
  $\begin{pmatrix}
1 & 2 & 3\\ 
0 & -1 & -2
\end{pmatrix}$

   Ранг = 2.

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

   3 строка является суммой первых двух, ее можно отбросить. Меняем строки местами.
   
   $\begin{pmatrix}
2 & 3 & 5 & 6\\ 
0 & 0 & 2 & 2\\
0 & 0 & 2 & 1
\end{pmatrix}$
   
   Ранг = 3.

In [25]:
a=np.array([[1,2,3],[1,1,1],[2,3,4]])
b=np.array([[0,0,2,1],[0,0,2,2],[0,0,4,3],[2,3,5,6]])

print(f'Ранг матрицы а = {np.linalg.matrix_rank(a)}')
print(f'Ранг матрицы б = {np.linalg.matrix_rank(b)}')

Ранг матрицы а = 2
Ранг матрицы б = 3
